runtime: nodejs10
env: standard

manual_scaling:
  instances: 1

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
  - url: .*
    secure: always
    redirect_http_response_code: 301
    script: auto
